/*
* Piccu Engine
* Copyright (C) 2024 SaladBadger
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

const char* blitVertexSrc =
"#version 450 core\n"
"\n"
"layout(location = 0) in vec2 position;\n"
"layout(location = 1) in vec2 uv;\n"
"\n"
"out vec2 outuv;\n"
"\n"
"void main()\n"
"{\n"
"gl_Position = vec4(position, 0.0, 1.0);\n"
"outuv = uv;"
"}\n"
"";

const char* blitFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"\n"
"out vec4 color;\n"
"\n "
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"uniform vec2 uv_origin;\n"
"uniform vec2 uv_scale;\n"
"\n"
"void main()\n"
"{\n"
"vec2 sample_uv = uv_origin + outuv * uv_scale;\n"
"vec4 sourcecolor = texture(heh, sample_uv);\n"
"color = vec4(pow(sourcecolor.rgb, vec3(gamma)), sourcecolor.a);\n"
"}\n"
"";

const char* motionVectorDebugFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D velocity_source;\n"
"uniform vec2 uv_origin;\n"
"uniform vec2 uv_scale;\n"
"uniform vec2 screen_size;\n"
"\n"
"void main()\n"
"{\n"
"	vec2 velocity = texture(velocity_source, uv_origin + outuv * uv_scale).xy;\n"
"	vec2 pixels = velocity * screen_size;\n"
"	vec2 signed_vis = sign(pixels) * (1.0 - exp(-abs(pixels) * 4.0));\n"
"	float mag = 1.0 - exp(-length(pixels) * 4.0);\n"
"	vec3 directional = vec3(max(signed_vis.x, 0.0), max(-signed_vis.x, 0.0), abs(signed_vis.y));\n"
"	color = vec4(max(directional, vec3(mag * 0.12)), clamp(mag * 0.85, 0.0, 0.85));\n"
"}\n"
"";

const char* pixelMotionBlurFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D color_source;\n"
"uniform sampler2D velocity_source;\n"
"uniform sampler2D protection_mask;\n"
"uniform int use_protection_mask;\n"
"uniform vec2 velocity_uv_origin;\n"
"uniform vec2 velocity_uv_scale;\n"
"uniform float strength;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 base = texture(color_source, outuv);\n"
"	vec2 mask_uv = velocity_uv_origin + outuv * velocity_uv_scale;\n"
"	if (use_protection_mask != 0)\n"
"	{\n"
"		vec4 mask = texture(protection_mask, mask_uv);\n"
"		float protection = clamp(max(mask.r, mask.g), 0.0, 1.0);\n"
"		if (protection >= 0.999)\n"
"		{\n"
"			color = base;\n"
"			return;\n"
"		}\n"
"	}\n"
"	vec2 velocity = texture(velocity_source, mask_uv).xy;\n"
"	vec2 blur = clamp(velocity * strength, vec2(-0.08), vec2(0.08));\n"
"	if (strength <= 0.0 || dot(blur, blur) < 0.0000000001)\n"
"	{\n"
"		color = base;\n"
"		return;\n"
"	}\n"
"	const int samples = 9;\n"
"	vec4 accum = vec4(0.0);\n"
"	for (int i = 0; i < samples; ++i)\n"
"	{\n"
"		float t = float(i) / float(samples - 1) - 0.5;\n"
"		vec2 sample_uv = clamp(outuv - blur * t, vec2(0.0), vec2(1.0));\n"
"		vec4 sample_color = texture(color_source, sample_uv);\n"
"		if (use_protection_mask != 0)\n"
"		{\n"
"			vec2 sample_mask_uv = velocity_uv_origin + sample_uv * velocity_uv_scale;\n"
"			vec4 sample_mask = texture(protection_mask, sample_mask_uv);\n"
"			float sample_protection = clamp(max(sample_mask.r, sample_mask.g), 0.0, 1.0);\n"
"			sample_color = mix(sample_color, base, sample_protection);\n"
"		}\n"
"		accum += sample_color;\n"
"	}\n"
"	vec4 blurred = accum / float(samples);\n"
"	if (use_protection_mask != 0)\n"
"	{\n"
"		vec4 mask = texture(protection_mask, mask_uv);\n"
"		float protection = clamp(max(mask.r, mask.g), 0.0, 1.0);\n"
"		color = mix(blurred, base, protection);\n"
"	}\n"
"	else\n"
"	{\n"
"		color = blurred;\n"
"	}\n"
"}\n"
"";

const char* fontVertexSrc =
"#version 450 core\n"
"\n"
"layout(std140) uniform CommonBlock\n"
"{\n"
"	mat4 projection;\n"
"	mat4 modelview;\n"
"} commons;\n"
"\n"
"layout(location = 0) in vec3 position;\n"
"layout(location = 1) in vec4 color;\n"
"layout(location = 2) in vec3 uv;\n"
"layout(location = 3) in vec3 uv2;\n"
"\n"
"out vec4 outcolor;\n"
"out vec2 outuv;\n"
"flat out int outlayer;\n"
"\n"
"void main()\n"
"{\n"
"	gl_Position = commons.projection * commons.modelview * vec4(position, 1.0);\n"
"	outcolor = color;\n"
"	outuv = uv.xy;\n"
"	outlayer = int(uv2.x + 0.5);\n"
"}\n"
"";

const char* fontFragmentSrc =
"#version 450 core\n"
"\n"
"uniform sampler2DArray fonttexture;\n"
"\n"
"in vec4 outcolor;\n"
"in vec2 outuv;\n"
"flat in int outlayer;\n"
"\n"
"layout(location = 0) out vec4 color;\n"
"layout(location = 2) out vec4 post_mask;\n"
"layout(location = 3) out float ao_class;\n"
"\n"
"void main()\n"
"{\n"
"	color = texture(fonttexture, vec3(outuv, float(outlayer))) * outcolor;\n"
"	float suppression = clamp(1.0 - pow(1.0 - clamp(color.a, 0.0, 1.0), 3.0), 0.0, 1.0);\n"
"	post_mask = vec4(suppression, suppression, 0.0, 1.0);\n"
"	ao_class = 1.0;\n"
"}\n"
"";

const char* downsampleFragmentSrc =
"#version 450 core\n"
"\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"uniform ivec2 dest_origin;\n"
"uniform ivec2 source_visible_origin;\n"
"uniform ivec2 source_visible_size;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec4 WronskiFilter(ivec2 dst)\n"
"{\n"
"	const float d0 = 0.75777;\n"
"	const float d1 = 2.907;\n"
"	const float w0 = 0.37487566;\n"
"	const float w1 = -0.12487566;\n"
"	vec2 inv_source_size = 1.0 / vec2(textureSize(heh, 0));\n"
"	vec2 uv = (vec2(dst) * 2.0 + vec2(1.0)) * inv_source_size;\n"
"	vec2 uv_min = vec2(0.0);\n"
"	vec2 uv_max = vec2(1.0);\n"
"	if (source_visible_size.x > 0 && source_visible_size.y > 0)\n"
"	{\n"
"		uv_min = (vec2(source_visible_origin) + vec2(0.5)) * inv_source_size;\n"
"		uv_max = (vec2(source_visible_origin + source_visible_size) - vec2(0.5)) * inv_source_size;\n"
"	}\n"
"	vec4 c0 = texture(heh, clamp(uv + vec2( d0,  d0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c1 = texture(heh, clamp(uv + vec2(-d0,  d0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c2 = texture(heh, clamp(uv + vec2( d0, -d0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c3 = texture(heh, clamp(uv + vec2(-d0, -d0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c4 = texture(heh, clamp(uv + vec2( d1,  0.0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c5 = texture(heh, clamp(uv + vec2(-d1,  0.0) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c6 = texture(heh, clamp(uv + vec2( 0.0,  d1) * inv_source_size, uv_min, uv_max));\n"
"	vec4 c7 = texture(heh, clamp(uv + vec2( 0.0, -d1) * inv_source_size, uv_min, uv_max));\n"
"	vec3 average = (ToDisplay(c0.rgb) + ToDisplay(c1.rgb) + ToDisplay(c2.rgb) + ToDisplay(c3.rgb)) * w0 +\n"
"		(ToDisplay(c4.rgb) + ToDisplay(c5.rgb) + ToDisplay(c6.rgb) + ToDisplay(c7.rgb)) * w1;\n"
"	float alpha = (c0.a + c1.a + c2.a + c3.a) * w0 + (c4.a + c5.a + c6.a + c7.a) * w1;\n"
"	return vec4(FromDisplay(average), clamp(alpha, 0.0, 1.0));\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	ivec2 dst = ivec2(gl_FragCoord.xy) - dest_origin;\n"
"	color = WronskiFilter(dst);\n"
"}\n"
"";

const char* bloomThresholdFragmentSrc =
// Bloom downsample and merge filter structure is adapted from The Force Engine
// (https://github.com/luciusDXL/TheForceEngine), GPL-2.0. Piccu's source
// extraction differs: it thresholds the resolved scene color instead of using
// TFE's generated emissive/material mask.
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D depth_source;\n"
"uniform sampler2D protection_mask;\n"
"uniform float gamma;\n"
"uniform float bloom_threshold;\n"
"uniform int use_depth_mask;\n"
"uniform int use_protection_mask;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec3 SampleBloom(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	vec2 sampleuv = uv + step * vec2(x, y);\n"
"	if (use_depth_mask != 0 && texture(depth_source, sampleuv).r >= 0.99999)\n"
"		return vec3(0.0);\n"
"	if (use_protection_mask != 0)\n"
"	{\n"
"		ivec2 mask_size = textureSize(protection_mask, 0);\n"
"		ivec2 mask_px = ivec2(clamp(sampleuv, vec2(0.0), vec2(0.999999)) * vec2(mask_size));\n"
"		vec2 mask = texelFetch(protection_mask, mask_px, 0).rg;\n"
"		float protection = clamp(mask.g, 0.0, 1.0);\n"
"		if (protection >= 1.0)\n"
"			return vec3(0.0);\n"
"		vec3 displaycolor = ToDisplay(texture(heh, sampleuv).rgb);\n"
"		float brightness = max(max(displaycolor.r, displaycolor.g), displaycolor.b);\n"
"		float threshold_range = max(1.0 - bloom_threshold, 0.0001);\n"
"		float amount = clamp((brightness - bloom_threshold) / threshold_range, 0.0, 1.0);\n"
"		return displaycolor * amount * (1.0 - protection);\n"
"	}\n"
"	vec3 displaycolor = ToDisplay(texture(heh, sampleuv).rgb);\n"
"	float brightness = max(max(displaycolor.r, displaycolor.g), displaycolor.b);\n"
"	float threshold_range = max(1.0 - bloom_threshold, 0.0001);\n"
"	float amount = clamp((brightness - bloom_threshold) / threshold_range, 0.0, 1.0);\n"
"	return displaycolor * amount;\n"
"}\n"
"\n"
"vec3 SmoothBloomDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleBloom(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleBloom(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleBloom(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleBloom(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleBloom(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleBloom(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleBloom(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleBloom(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleBloom(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleBloom(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleBloom(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleBloom(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleBloom(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(FromDisplay(SmoothBloomDownsample(outuv, step)), 1.0);\n"
"}\n"
"";

const char* bloomDownsampleFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"\n"
"vec3 SampleWithStep(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	return texture(heh, uv + step * vec2(x, y)).rgb;\n"
"}\n"
"\n"
"vec3 SmoothDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleWithStep(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleWithStep(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleWithStep(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleWithStep(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleWithStep(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleWithStep(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleWithStep(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleWithStep(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleWithStep(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleWithStep(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleWithStep(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleWithStep(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleWithStep(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(SmoothDownsample(outuv, step), 1.0);\n"
"}\n"
"";

const char* bloomMergeFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D MergeCur;\n"
"uniform sampler2D MergePrev;\n"
"uniform float bloomSpread;\n"
"\n"
"vec3 Blur3x3(sampler2D source, vec2 uv, vec2 scale)\n"
"{\n"
"	const float weights[9] = float[9](0.0625, 0.125, 0.0625, 0.125, 0.25, 0.125, 0.0625, 0.125, 0.0625);\n"
"	vec3 sum = vec3(0.0);\n"
"	int i = 0;\n"
"	for (int y = -1; y <= 1; y++)\n"
"	{\n"
"		for (int x = -1; x <= 1; x++, i++)\n"
"			sum += texture(source, uv + vec2(x, y) * scale).rgb * weights[i];\n"
"	}\n"
"	return sum;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	float blurScale = 1.5;\n"
"	vec3 curSample = texture(MergeCur, outuv).rgb;\n"
"	vec2 scaleUpsampled = vec2(blurScale) / vec2(textureSize(MergePrev, 0));\n"
"	vec3 upsampled = Blur3x3(MergePrev, outuv, scaleUpsampled);\n"
"	color = vec4(mix(curSample, upsampled, bloomSpread), 1.0);\n"
"}\n"
"";

const char* bloomCompositeFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D bloom;\n"
"uniform sampler2D scene_source;\n"
"uniform sampler2D protection_mask;\n"
"uniform float gamma;\n"
"uniform float bloom_intensity;\n"
"uniform int use_alpha_mask;\n"
"uniform int use_protection_mask;\n"
"uniform vec2 uv_origin;\n"
"uniform vec2 uv_scale;\n"
"uniform vec2 scene_uv_origin;\n"
"uniform vec2 scene_uv_scale;\n"
"\n"
"void main()\n"
"{\n"
"	vec2 sample_uv = uv_origin + outuv * uv_scale;\n"
"	vec2 scene_uv = scene_uv_origin + outuv * scene_uv_scale;\n"
"	vec4 sourcecolor = texture(heh, scene_uv);\n"
"	vec3 bloomcolor = texture(bloom, sample_uv).rgb * bloom_intensity;\n"
"	float scene_mask = (use_alpha_mask != 0) ? 1.0 - clamp(sourcecolor.a, 0.0, 1.0) : 1.0;\n"
"	if (use_protection_mask != 0)\n"
"	{\n"
"		ivec2 mask_size = textureSize(protection_mask, 0);\n"
"		ivec2 mask_px = ivec2(clamp(sample_uv, vec2(0.0), vec2(0.999999)) * vec2(mask_size));\n"
"		vec2 mask = texelFetch(protection_mask, mask_px, 0).rg;\n"
"		scene_mask *= 1.0 - clamp(mask.g, 0.0, 1.0);\n"
"	}\n"
"	color = vec4(pow(max(sourcecolor.rgb + bloomcolor * scene_mask, vec3(0.0)), vec3(gamma)), 1.0);\n"
"}\n"
"";

const char* aoDeferredCompositeFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D final_source;\n"
"uniform sampler2D scene_source;\n"
"uniform sampler2D ao_scene_source;\n"
"uniform sampler2D protection_mask;\n"
"uniform int use_protection_mask;\n"
"uniform vec2 visible_origin;\n"
"uniform vec2 visible_size;\n"
"uniform int use_visible_rect;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 final_color = texture(final_source, outuv);\n"
"	vec3 scene_color = texture(scene_source, outuv).rgb;\n"
"	vec3 ao_scene_color = texture(ao_scene_source, outuv).rgb;\n"
"	float scene_mask = 1.0 - clamp(final_color.a, 0.0, 1.0);\n"
"	if (use_visible_rect != 0)\n"
"	{\n"
"		vec2 local = gl_FragCoord.xy - visible_origin;\n"
"		if (local.x < 0.0 || local.y < 0.0 || local.x >= visible_size.x || local.y >= visible_size.y)\n"
"			scene_mask = 0.0;\n"
"	}\n"
"	if (use_protection_mask != 0)\n"
"	{\n"
"		ivec2 mask_size = textureSize(protection_mask, 0);\n"
"		ivec2 mask_px = ivec2(clamp(outuv, vec2(0.0), vec2(0.999999)) * vec2(mask_size));\n"
"		float ao_protection = texelFetch(protection_mask, mask_px, 0).r;\n"
"		scene_mask *= 1.0 - clamp(ao_protection, 0.0, 1.0);\n"
"	}\n"
"	color = vec4(max(final_color.rgb + (ao_scene_color - scene_color) * scene_mask, vec3(0.0)), final_color.a);\n"
"}\n"
"";

const char* testVertexSrc =
"#version 450 core\n"
"\n"
"layout(std140) uniform CommonBlock\n"
"{\n"
"	mat4 projection;\n"
"	mat4 modelview;\n"
"} commons;\n"
"\n"
"layout(location = 0) in vec3 position;\n"
"layout(location = 4) in vec2 uv;\n"
"layout(location = 5) in vec2 uv2;\n"
"\n"
"out vec2 outuv;\n"
"out vec2 outuv2;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 temp = commons.modelview * vec4(position, 1.0);\n"
"	gl_Position = commons.projection * vec4(temp.xyz, temp.w);\n"
"	outuv = uv;\n"
"	outuv2 = uv2;\n"
"}\n"
"";

const char* testFragmentSrc =
"#version 450 core\n"
"\n"
"uniform sampler2D colortexture;\n"
"uniform sampler2D lightmaptexture;\n"
"\n"
"in vec2 outuv;\n"
"in vec2 outuv2;\n"
"\n"
"out vec4 color;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 basecolor = texture(colortexture, outuv);\n"
"	color = vec4(basecolor.rgb * texture(lightmaptexture, outuv2).rgb, basecolor.a);\n"
"}\n"
"";

//-----------------------------------------------------------------------------
// GTAO (Ground-Truth Ambient Occlusion) shaders.
//
// The algorithm walks paired rays in screen space from each pixel and uses
// the strongest observed horizon along each direction as the occlusion term.
// The resulting AO factor is bilaterally blurred with depth weighting and
// then multiplied into the scene color.
//
// Inputs:
//   depth_tex : source depth reduced to the AO working resolution.
//   noise_tex : 4x4 noise (R8) for random sample rotation.
//
// View-space convention (in the AO shader):
//   x increases right, y increases up, z = +depth (positive into scene).
//   Reconstructed normal points TOWARD the camera (negative z).
//-----------------------------------------------------------------------------

const char* gtaoDepthFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"layout(location = 0) out vec4 result;\n"
"\n"
"uniform sampler2D depth_tex;\n"
"uniform sampler2DMS depth_ms_tex;\n"
"uniform sampler2D ao_class_tex;\n"
"uniform int depth_samples;\n"
"uniform int has_ao_class;\n"
"uniform int ao_weight_is_direct;\n"
"uniform vec2 input_screen_size;\n"
"uniform vec2 ao_screen_size;\n"
"uniform float terrain_ao_occlusion;\n"
"uniform float polyobject_ao_occlusion;\n"
"uniform float mine_rock_ao_occlusion;\n"
"uniform float mine_ao_occlusion;\n"
"\n"
"struct DepthWeight\n"
"{\n"
"    float depth;\n"
"    float ao_weight;\n"
"};\n"
"\n"
"float FetchDepth(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    float d = 1.0;\n"
"    if (depth_samples > 1)\n"
"    {\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= depth_samples) break;\n"
"            d = min(d, texelFetch(depth_ms_tex, pixel, i).r);\n"
"        }\n"
"    }\n"
"    else\n"
"    {\n"
"        d = texelFetch(depth_tex, pixel, 0).r;\n"
"    }\n"
"    return d;\n"
"}\n"
"\n"
"float AOClassWeight(float encoded_class)\n"
"{\n"
"    float value = floor(encoded_class * 255.0 + 0.5);\n"
"    if (value == 1.0)\n"
"        return clamp(terrain_ao_occlusion, 0.0, 1.0);\n"
"    if (value == 2.0)\n"
"        return clamp(polyobject_ao_occlusion, 0.0, 1.0);\n"
"    if (value == 3.0)\n"
"        return clamp(mine_rock_ao_occlusion, 0.0, 1.0);\n"
"    if (value == 4.0)\n"
"        return clamp(mine_ao_occlusion, 0.0, 1.0);\n"
"    return 1.0;\n"
"}\n"
"\n"
"DepthWeight FetchDepthWeight(ivec2 pixel)\n"
"{\n"
"    DepthWeight value;\n"
"    value.depth = FetchDepth(pixel);\n"
"    value.ao_weight = 1.0;\n"
"    if (has_ao_class != 0)\n"
"    {\n"
"        vec2 uv = (vec2(pixel) + vec2(0.5)) / input_screen_size;\n"
"        float stored_value = texture(ao_class_tex, uv).r;\n"
"        value.ao_weight = (ao_weight_is_direct != 0) ? clamp(stored_value, 0.0, 1.0) : AOClassWeight(stored_value);\n"
"    }\n"
"    return value;\n"
"}\n"
"\n"
"DepthWeight MinDepthWeight(DepthWeight a, DepthWeight b)\n"
"{\n"
"    return (b.depth < a.depth) ? b : a;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    //Cost of this pass scaled with source_W * source_H regardless of\n"
"    //gtao_resolution, which is why the F2 slider used to barely move perf.\n"
"    //A fixed 2x2 min covers typical 2x-4x downsample ratios; the AO horizon\n"
"    //march is a low-frequency screen-space approximation and does not need\n"
"    //a conservative min over the entire source footprint.\n"
"    ivec2 ao_pixel = ivec2(gl_FragCoord.xy);\n"
"    ivec2 input_size = ivec2(input_screen_size);\n"
"    vec2 src_center = (vec2(ao_pixel) + vec2(0.5)) * (input_screen_size / ao_screen_size);\n"
"    ivec2 src_origin = ivec2(floor(src_center - vec2(0.5)));\n"
"    ivec2 p00 = clamp(src_origin,                  ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p10 = clamp(src_origin + ivec2(1, 0),    ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p01 = clamp(src_origin + ivec2(0, 1),    ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p11 = clamp(src_origin + ivec2(1, 1),    ivec2(0), input_size - ivec2(1));\n"
"    DepthWeight best = FetchDepthWeight(p00);\n"
"    best = MinDepthWeight(best, FetchDepthWeight(p10));\n"
"    best = MinDepthWeight(best, FetchDepthWeight(p01));\n"
"    best = MinDepthWeight(best, FetchDepthWeight(p11));\n"
"    result = vec4(best.depth, best.ao_weight, 0.0, 1.0);\n"
"}\n"
"";

const char* gtaoAOFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"layout(location = 0) out vec4 ao_out;\n"
"\n"
"uniform sampler2D depth_tex;\n"
"uniform sampler2D noise_tex;\n"
"\n"
"//Projection helpers: pack (2/m00, 2/m11, -1/m00, -1/m11) so that\n"
"//  view.xy = (uv * proj_info.xy + proj_info.zw) * depth;\n"
"uniform vec4 proj_info;\n"
"uniform vec2 near_far;       // (nearZ, farZ)\n"
"uniform float radius;        // world-space radius\n"
"uniform float radius_pixels; // pixel-space radius when depth == 1\n"
"uniform float max_radius_pixels;\n"
"uniform float neg_inv_radius2;\n"
"uniform float angle_bias;\n"
"uniform vec2 inv_screen_size;\n"
"uniform vec2 ao_inv_screen_size;\n"
"uniform vec2 screen_size;\n"
"uniform vec2 noise_origin;\n"
"uniform int directions;\n"
"uniform int steps;\n"
"const float PI = 3.14159265358979323846;\n"
"\n"
"float linearize_depth(float d)\n"
"{\n"
"    //OpenGL clip-space z is [-1,1] after divide; FBO depth is [0,1].\n"
"    float z_n = 2.0 * d - 1.0;\n"
"    float n = near_far.x;\n"
"    float f = near_far.y;\n"
"    return (2.0 * n * f) / (f + n - z_n * (f - n));\n"
"}\n"
"\n"
"vec3 fetch_view_pos(vec2 uv)\n"
"{\n"
"    //Clamp only the texture lookup. Keeping the original UV for projection\n"
"    //prevents offscreen samples from collapsing onto the screen edge.\n"
"    vec2 depth_uv = clamp(uv, vec2(0.0), vec2(1.0) - ao_inv_screen_size * 0.5);\n"
"    float d = linearize_depth(texture(depth_tex, depth_uv).r);\n"
"    vec3 p;\n"
"    p.xy = (uv * proj_info.xy + proj_info.zw) * d;\n"
"    p.z = d;\n"
"    return p;\n"
"}\n"
"\n"
"vec3 min_diff(vec3 P, vec3 Pr, vec3 Pl)\n"
"{\n"
"    vec3 V1 = Pr - P;\n"
"    vec3 V2 = P - Pl;\n"
"    return (dot(V1, V1) < dot(V2, V2)) ? V1 : V2;\n"
"}\n"
"\n"
"vec3 reconstruct_normal(vec2 uv, vec3 P)\n"
"{\n"
"    vec3 Pr = fetch_view_pos(uv + vec2(ao_inv_screen_size.x, 0.0));\n"
"    vec3 Pl = fetch_view_pos(uv + vec2(-ao_inv_screen_size.x, 0.0));\n"
"    vec3 Pt = fetch_view_pos(uv + vec2(0.0, ao_inv_screen_size.y));\n"
"    vec3 Pb = fetch_view_pos(uv + vec2(0.0, -ao_inv_screen_size.y));\n"
"    //Cross(dx, dy) in our LH (x right, y up, z = +depth into scene) gives\n"
"    //+z = into the scene. We want a vector facing the camera, so negate.\n"
"    return -normalize(cross(min_diff(P, Pr, Pl), min_diff(P, Pt, Pb)));\n"
"}\n"
"\n"
"float falloff(float dist_sq)\n"
"{\n"
"    return dist_sq * neg_inv_radius2 + 1.0;\n"
"}\n"
"\n"
"float fetch_ao_weight(vec2 uv)\n"
"{\n"
"    vec2 depth_uv = clamp(uv, vec2(0.0), vec2(1.0) - ao_inv_screen_size * 0.5);\n"
"    return clamp(texture(depth_tex, depth_uv).g, 0.0, 1.0);\n"
"}\n"
"\n"
"float compute_gtao_horizon(vec3 P, vec3 N, vec2 dir, float step_pixels, float jitter, float side)\n"
"{\n"
"    float ray_pixels = jitter * step_pixels + 1.0;\n"
"    float horizon = 0.0;\n"
"    float average = 0.0;\n"
"    for (int s = 0; s < steps; ++s)\n"
"    {\n"
"        vec2 sample_uv = (round(ray_pixels * dir * side) * ao_inv_screen_size) + outuv;\n"
"        vec3 S = fetch_view_pos(sample_uv);\n"
"        float sample_weight = fetch_ao_weight(sample_uv);\n"
"        vec3 V = S - P;\n"
"        float VdotV = dot(V, V);\n"
"        float NdotV = dot(N, V) * inversesqrt(max(VdotV, 1e-6));\n"
"        float sample_horizon = max(NdotV - angle_bias, 0.0) * clamp(falloff(VdotV), 0.0, 1.0);\n"
"        sample_horizon *= sample_weight;\n"
"        horizon = max(horizon, sample_horizon);\n"
"        average += sample_horizon;\n"
"        ray_pixels += step_pixels;\n"
"    }\n"
"    average /= max(float(steps), 1.0);\n"
"    return mix(average, horizon, 0.75);\n"
"}\n"
"\n"
"vec2 fetch_noise(vec2 screen_pos)\n"
"{\n"
"    return texture(noise_tex, screen_pos / 4.0).rg;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec3 P = fetch_view_pos(outuv);\n"
"    //Output linearized depth as the .y channel for the bilateral blur weight.\n"
"    float depth_for_blur = clamp(P.z / max(near_far.y, 1e-4), 0.0, 1.0);\n"
"\n"
"    //Avoid running on far-plane sky pixels.\n"
"    if (P.z >= near_far.y * 0.999)\n"
"    {\n"
"        ao_out = vec4(1.0, depth_for_blur, 0.0, 1.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 N = reconstruct_normal(outuv, P);\n"
"\n"
"    //Step size in pixels. Sample radius shrinks with depth (perspective).\n"
"    float step_pixels = min(radius_pixels / max(P.z, 1e-3), max_radius_pixels);\n"
"    step_pixels = step_pixels / float(steps + 1);\n"
"\n"
"    //Per-pixel noise: cos/sin angle in .r, sample jitter in .g.\n"
"    vec2 screen_pos = outuv * screen_size - noise_origin;\n"
"    vec2 rand = fetch_noise(screen_pos);\n"
"\n"
"    float ao = 0.0;\n"
"    int gtao_directions = max((directions + 1) / 2, 1);\n"
"    float alpha = PI / float(gtao_directions);\n"
"    for (int d = 0; d < gtao_directions; ++d)\n"
"    {\n"
"        float angle = alpha * (float(d) + rand.x);\n"
"        vec2 dir = vec2(cos(angle), sin(angle));\n"
"        float jitter = fract(rand.y + float(d) * 0.61803398875);\n"
"        ao += compute_gtao_horizon(P, N, dir, step_pixels, jitter, 1.0);\n"
"        ao += compute_gtao_horizon(P, N, dir, step_pixels, jitter, -1.0);\n"
"    }\n"
"    ao = ao / max(float(gtao_directions) * 2.0, 1.0);\n"
"    ao = ao / max(1.0 - angle_bias, 0.01);\n"
"\n"
"    ao = clamp(1.0 - ao, 0.0, 1.0);\n"
"\n"
"    ao_out = vec4(ao, depth_for_blur, 0.0, 1.0);\n"
"}\n"
"";

const char* gtaoBlurFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D heh;       // RG: x=AO, y=linear depth in [0,1]\n"
"uniform vec2 blur_delta;     // (1/w, 0) or (0, 1/h)\n"
"uniform float sharpness;     // higher = sharper edges\n"
"uniform int kernel_radius;   // 0 means just passthrough\n"
"\n"
"void main()\n"
"{\n"
"    vec2 center = texture(heh, outuv).xy;\n"
"    float center_ao = center.x;\n"
"    float center_z = center.y;\n"
"    if (kernel_radius <= 0)\n"
"    {\n"
"        result = vec4(center_ao, center_z, 0.0, 1.0);\n"
"        return;\n"
"    }\n"
"    float sigma = float(kernel_radius) * 0.5;\n"
"    float falloff = 1.0 / (2.0 * sigma * sigma);\n"
"    float total_ao = center_ao;\n"
"    float total_w = 1.0;\n"
"    for (int r = 1; r <= 20; ++r)\n"
"    {\n"
"        if (r > kernel_radius) break;\n"
"        vec2 uv_p = outuv + float(r) * blur_delta;\n"
"        vec2 uv_n = outuv - float(r) * blur_delta;\n"
"        vec2 sp = texture(heh, uv_p).xy;\n"
"        vec2 sn = texture(heh, uv_n).xy;\n"
"        float dzp = (center_z - sp.y) * sharpness;\n"
"        float dzn = (center_z - sn.y) * sharpness;\n"
"        float wp = exp2(-float(r * r) * falloff - dzp * dzp);\n"
"        float wn = exp2(-float(r * r) * falloff - dzn * dzn);\n"
"        total_ao += sp.x * wp + sn.x * wn;\n"
"        total_w += wp + wn;\n"
"    }\n"
"    total_ao /= max(total_w, 1e-6);\n"
"    result = vec4(total_ao, center_z, 0.0, 1.0);\n"
"}\n"
"";

const char* gtaoSuppressionFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D existing_mask;\n"
"uniform sampler2DMS existing_mask_ms;\n"
"uniform sampler2D color_tex;\n"
"uniform sampler2DMS color_ms_tex;\n"
"uniform int has_mask;\n"
"uniform int use_bloom_mask;\n"
"uniform int source_samples;\n"
"uniform vec2 input_screen_size;\n"
"uniform vec2 ao_screen_size;\n"
"uniform vec2 source_visible_origin;\n"
"uniform vec2 source_visible_size;\n"
"uniform int use_source_visible_rect;\n"
"uniform float gamma;\n"
"uniform float bloom_threshold;\n"
"\n"
"bool SourceVisibleUV(ivec2 pixel, out vec2 uv)\n"
"{\n"
"    if (use_source_visible_rect == 0)\n"
"    {\n"
"        uv = (vec2(pixel) + vec2(0.5)) / input_screen_size;\n"
"        return true;\n"
"    }\n"
"    vec2 local = vec2(pixel) - source_visible_origin;\n"
"    if (local.x < 0.0 || local.y < 0.0 || local.x >= source_visible_size.x || local.y >= source_visible_size.y)\n"
"    {\n"
"        uv = vec2(0.0);\n"
"        return false;\n"
"    }\n"
"    uv = (local + vec2(0.5)) / source_visible_size;\n"
"    return true;\n"
"}\n"
"\n"
"float MaskAtPixel(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    vec2 uv;\n"
"    if (!SourceVisibleUV(pixel, uv))\n"
"        return 0.0;\n"
"    if (source_samples > 1)\n"
"    {\n"
"        ivec2 mask_size = textureSize(existing_mask_ms);\n"
"        ivec2 mask_pixel = clamp(ivec2(uv * vec2(mask_size)), ivec2(0), mask_size - ivec2(1));\n"
"        float mask = 0.0;\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= source_samples) break;\n"
"            mask = max(mask, texelFetch(existing_mask_ms, mask_pixel, i).r);\n"
"        }\n"
"        return mask;\n"
"    }\n"
"    ivec2 mask_size = textureSize(existing_mask, 0);\n"
"    ivec2 mask_pixel = clamp(ivec2(uv * vec2(mask_size)), ivec2(0), mask_size - ivec2(1));\n"
"    return texelFetch(existing_mask, mask_pixel, 0).r;\n"
"}\n"
"\n"
"float BloomAmountFromColor(vec3 color)\n"
"{\n"
"    vec3 display_color = pow(max(color, vec3(0.0)), vec3(gamma));\n"
"    float brightness = max(max(display_color.r, display_color.g), display_color.b);\n"
"    float range = max(1.0 - bloom_threshold, 0.0001);\n"
"    return clamp((brightness - bloom_threshold) / range, 0.0, 1.0);\n"
"}\n"
"\n"
"float BloomAtPixel(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    vec2 uv;\n"
"    if (!SourceVisibleUV(pixel, uv))\n"
"        return 0.0;\n"
"    if (source_samples > 1)\n"
"    {\n"
"        float bloom = 0.0;\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= source_samples) break;\n"
"            bloom = max(bloom, BloomAmountFromColor(texelFetch(color_ms_tex, pixel, i).rgb));\n"
"        }\n"
"        return bloom;\n"
"    }\n"
"    ivec2 color_size = textureSize(color_tex, 0);\n"
"    ivec2 color_pixel = clamp(ivec2(uv * vec2(color_size)), ivec2(0), color_size - ivec2(1));\n"
"    return BloomAmountFromColor(texelFetch(color_tex, color_pixel, 0).rgb);\n"
"}\n"
"\n"
"void SourceBlock(out ivec2 src_min, out ivec2 src_max)\n"
"{\n"
"    ivec2 ao_pixel = ivec2(gl_FragCoord.xy);\n"
"    ivec2 input_size = ivec2(input_screen_size);\n"
"    vec2 src_min_f = floor(vec2(ao_pixel) * input_screen_size / ao_screen_size);\n"
"    vec2 src_max_f = ceil(vec2(ao_pixel + ivec2(1)) * input_screen_size / ao_screen_size);\n"
"    src_min = clamp(ivec2(src_min_f), ivec2(0), input_size - ivec2(1));\n"
"    src_max = clamp(max(ivec2(src_max_f), src_min + ivec2(1)), ivec2(1), input_size);\n"
"}\n"
"\n"
"float MaskAmount()\n"
"{\n"
"    if (has_mask == 0)\n"
"        return 0.0;\n"
"    ivec2 src_min;\n"
"    ivec2 src_max;\n"
"    SourceBlock(src_min, src_max);\n"
"    float mask = 0.0;\n"
"    float count = 0.0;\n"
"    for (int y = 0; y < 8; ++y)\n"
"    {\n"
"        int py = src_min.y + y;\n"
"        if (py >= src_max.y) break;\n"
"        for (int x = 0; x < 8; ++x)\n"
"        {\n"
"            int px = src_min.x + x;\n"
"            if (px >= src_max.x) break;\n"
"            mask += MaskAtPixel(ivec2(px, py));\n"
"            count += 1.0;\n"
"        }\n"
"    }\n"
"    return mask / max(count, 1.0);\n"
"}\n"
"\n"
"float BloomAmount()\n"
"{\n"
"    if (use_bloom_mask == 0)\n"
"        return 0.0;\n"
"    ivec2 src_min;\n"
"    ivec2 src_max;\n"
"    SourceBlock(src_min, src_max);\n"
"    float bloom = 0.0;\n"
"    for (int y = 0; y < 8; ++y)\n"
"    {\n"
"        int py = src_min.y + y;\n"
"        if (py >= src_max.y) break;\n"
"        for (int x = 0; x < 8; ++x)\n"
"        {\n"
"            int px = src_min.x + x;\n"
"            if (px >= src_max.x) break;\n"
"            bloom = max(bloom, BloomAtPixel(ivec2(px, py)));\n"
"        }\n"
"    }\n"
"    return bloom;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    float suppression = MaskAmount();\n"
"    if (use_bloom_mask != 0)\n"
"    {\n"
"        float bloom = BloomAmount();\n"
"        suppression = max(suppression, bloom);\n"
"    }\n"
"    result = vec4(clamp(suppression, 0.0, 1.0), 0.0, 0.0, 1.0);\n"
"}\n"
"";

//Apply pass: multiplies destination color by the AO factor.
//Uses (GL_DST_COLOR, GL_ZERO) blend, so the output color is the AO multiplier.
const char* gtaoApplyFragmentSrc =
"#version 450 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D heh;       // RG: x=AO factor 0..1, y=depth\n"
"uniform sampler2D suppression_mask; // R8: 0=apply AO, 1=suppress AO\n"
"uniform float intensity;     // 0..4-ish; AO raised to this power\n"
"uniform int has_suppression_mask;\n"
"uniform vec2 ao_uv_origin;\n"
"uniform vec2 ao_uv_scale;\n"
"\n"
"void main()\n"
"{\n"
"    vec2 ao_uv = ao_uv_origin + outuv * ao_uv_scale;\n"
"    vec2 ao_depth = texture(heh, ao_uv).xy;\n"
"    float ao = ao_depth.x;\n"
"    ao = clamp(ao, 0.0, 1.0);\n"
"    if (has_suppression_mask != 0)\n"
"    {\n"
"        float suppression = clamp(texture(suppression_mask, ao_uv).r, 0.0, 1.0);\n"
"        ao = mix(ao, 1.0, suppression);\n"
"    }\n"
"    ao = pow(ao, intensity);\n"
"    result = vec4(vec3(ao), 1.0);\n"
"}\n"
"";
