/*
* Piccu Engine
* Copyright (C) 2024 SaladBadger
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

const char* blitVertexSrc =
"#version 330 core\n"
"\n"
"layout(location = 0) in vec2 position;\n"
"layout(location = 1) in vec2 uv;\n"
"\n"
"out vec2 outuv;\n"
"\n"
"void main()\n"
"{\n"
"gl_Position = vec4(position, 0.0, 1.0);\n"
"outuv = uv;"
"}\n"
"";

const char* blitFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"\n"
"out vec4 color;\n"
"\n "
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"\n"
"void main()\n"
"{\n"
"vec4 sourcecolor = texture(heh, outuv);\n"
"color = vec4(pow(sourcecolor.rgb, vec3(gamma)), sourcecolor.a);\n"
"}\n"
"";

const char* downsampleFragmentSrc =
"#version 330 core\n"
"\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"uniform ivec2 dest_origin;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec4 WronskiFilter(ivec2 dst)\n"
"{\n"
"	const float d0 = 0.75777;\n"
"	const float d1 = 2.907;\n"
"	const float w0 = 0.37487566;\n"
"	const float w1 = -0.12487566;\n"
"	vec2 inv_source_size = 1.0 / vec2(textureSize(heh, 0));\n"
"	vec2 uv = (vec2(dst) * 2.0 + vec2(1.0)) * inv_source_size;\n"
"	vec4 c0 = texture(heh, uv + vec2( d0,  d0) * inv_source_size);\n"
"	vec4 c1 = texture(heh, uv + vec2(-d0,  d0) * inv_source_size);\n"
"	vec4 c2 = texture(heh, uv + vec2( d0, -d0) * inv_source_size);\n"
"	vec4 c3 = texture(heh, uv + vec2(-d0, -d0) * inv_source_size);\n"
"	vec4 c4 = texture(heh, uv + vec2( d1,  0.0) * inv_source_size);\n"
"	vec4 c5 = texture(heh, uv + vec2(-d1,  0.0) * inv_source_size);\n"
"	vec4 c6 = texture(heh, uv + vec2( 0.0,  d1) * inv_source_size);\n"
"	vec4 c7 = texture(heh, uv + vec2( 0.0, -d1) * inv_source_size);\n"
"	vec3 average = (ToDisplay(c0.rgb) + ToDisplay(c1.rgb) + ToDisplay(c2.rgb) + ToDisplay(c3.rgb)) * w0 +\n"
"		(ToDisplay(c4.rgb) + ToDisplay(c5.rgb) + ToDisplay(c6.rgb) + ToDisplay(c7.rgb)) * w1;\n"
"	float alpha = (c0.a + c1.a + c2.a + c3.a) * w0 + (c4.a + c5.a + c6.a + c7.a) * w1;\n"
"	return vec4(FromDisplay(average), clamp(alpha, 0.0, 1.0));\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	ivec2 dst = ivec2(gl_FragCoord.xy) - dest_origin;\n"
"	color = WronskiFilter(dst);\n"
"}\n"
"";

const char* bloomThresholdFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D depth_source;\n"
"uniform float gamma;\n"
"uniform float bloom_threshold;\n"
"uniform int use_depth_mask;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec3 SampleBloom(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	vec2 sampleuv = uv + step * vec2(x, y);\n"
"	if (use_depth_mask != 0 && texture(depth_source, sampleuv).r >= 0.9999)\n"
"		return vec3(0.0);\n"
"	vec3 displaycolor = ToDisplay(texture(heh, sampleuv).rgb);\n"
"	float brightness = max(max(displaycolor.r, displaycolor.g), displaycolor.b);\n"
"	float threshold_range = max(1.0 - bloom_threshold, 0.0001);\n"
"	float amount = clamp((brightness - bloom_threshold) / threshold_range, 0.0, 1.0);\n"
"	return displaycolor * amount;\n"
"}\n"
"\n"
"vec3 SmoothBloomDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleBloom(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleBloom(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleBloom(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleBloom(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleBloom(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleBloom(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleBloom(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleBloom(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleBloom(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleBloom(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleBloom(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleBloom(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleBloom(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(FromDisplay(SmoothBloomDownsample(outuv, step)), 1.0);\n"
"}\n"
"";

const char* bloomDownsampleFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"\n"
"vec3 SampleWithStep(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	return texture(heh, uv + step * vec2(x, y)).rgb;\n"
"}\n"
"\n"
"vec3 SmoothDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleWithStep(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleWithStep(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleWithStep(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleWithStep(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleWithStep(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleWithStep(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleWithStep(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleWithStep(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleWithStep(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleWithStep(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleWithStep(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleWithStep(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleWithStep(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(SmoothDownsample(outuv, step), 1.0);\n"
"}\n"
"";

const char* bloomMergeFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D MergeCur;\n"
"uniform sampler2D MergePrev;\n"
"uniform float bloomSpread;\n"
"\n"
"vec3 Blur3x3(sampler2D source, vec2 uv, vec2 scale)\n"
"{\n"
"	const float weights[9] = float[9](0.0625, 0.125, 0.0625, 0.125, 0.25, 0.125, 0.0625, 0.125, 0.0625);\n"
"	vec3 sum = vec3(0.0);\n"
"	int i = 0;\n"
"	for (int y = -1; y <= 1; y++)\n"
"	{\n"
"		for (int x = -1; x <= 1; x++, i++)\n"
"			sum += texture(source, uv + vec2(x, y) * scale).rgb * weights[i];\n"
"	}\n"
"	return sum;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	float blurScale = 1.5;\n"
"	vec3 curSample = texture(MergeCur, outuv).rgb;\n"
"	vec2 scaleUpsampled = vec2(blurScale) / vec2(textureSize(MergePrev, 0));\n"
"	vec3 upsampled = Blur3x3(MergePrev, outuv, scaleUpsampled);\n"
"	color = vec4(mix(curSample, upsampled, bloomSpread), 1.0);\n"
"}\n"
"";

const char* bloomCompositeFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D bloom;\n"
"uniform sampler2D scene_source;\n"
"uniform float gamma;\n"
"uniform float bloom_intensity;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 sourcecolor = texture(heh, outuv);\n"
"	vec3 scene_color = texture(scene_source, outuv).rgb;\n"
"	vec3 bloomcolor = texture(bloom, outuv).rgb * bloom_intensity;\n"
"	vec3 changed = abs(sourcecolor.rgb - scene_color);\n"
"	float changed_amount = max(max(changed.r, changed.g), changed.b);\n"
"	float scene_mask = 1.0 - smoothstep(0.002, 0.03, changed_amount);\n"
"	color = vec4(pow(max(sourcecolor.rgb + bloomcolor * scene_mask, vec3(0.0)), vec3(gamma)), 1.0);\n"
"}\n"
"";

const char* testVertexSrc =
"#version 330 core\n"
"\n"
"layout(std140) uniform CommonBlock\n"
"{\n"
"	mat4 projection;\n"
"	mat4 modelview;\n"
"} commons;\n"
"\n"
"layout(location = 0) in vec3 position;\n"
"layout(location = 4) in vec2 uv;\n"
"layout(location = 5) in vec2 uv2;\n"
"\n"
"out vec2 outuv;\n"
"out vec2 outuv2;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 temp = commons.modelview * vec4(position, 1.0);\n"
"	gl_Position = commons.projection * vec4(temp.xyz, temp.w);\n"
"	outuv = uv;\n"
"	outuv2 = uv2;\n"
"}\n"
"";

const char* testFragmentSrc =
"#version 330 core\n"
"\n"
"uniform sampler2D colortexture;\n"
"uniform sampler2D lightmaptexture;\n"
"\n"
"in vec2 outuv;\n"
"in vec2 outuv2;\n"
"\n"
"out vec4 color;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 basecolor = texture(colortexture, outuv);\n"
"	color = vec4(basecolor.rgb * texture(lightmaptexture, outuv2).rgb, basecolor.a);\n"
"}\n"
"";
