/*
* Piccu Engine
* Copyright (C) 2024 SaladBadger
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

const char* blitVertexSrc =
"#version 330 core\n"
"\n"
"layout(location = 0) in vec2 position;\n"
"layout(location = 1) in vec2 uv;\n"
"\n"
"out vec2 outuv;\n"
"\n"
"void main()\n"
"{\n"
"gl_Position = vec4(position, 0.0, 1.0);\n"
"outuv = uv;"
"}\n"
"";

const char* blitFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"\n"
"out vec4 color;\n"
"\n "
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"\n"
"void main()\n"
"{\n"
"vec4 sourcecolor = texture(heh, outuv);\n"
"color = vec4(pow(sourcecolor.rgb, vec3(gamma)), sourcecolor.a);\n"
"}\n"
"";

const char* motionVectorVertexSrc =
"#version 330 core\n"
"\n"
"layout(location = 0) in vec3 position;\n"
"layout(location = 1) in vec2 velocity_pixels;\n"
"\n"
"uniform vec2 screen_size;\n"
"out vec2 out_velocity;\n"
"\n"
"void main()\n"
"{\n"
"	vec2 ndc = vec2((position.x / screen_size.x) * 2.0 - 1.0,\n"
"		1.0 - (position.y / screen_size.y) * 2.0);\n"
"	gl_Position = vec4(ndc, -2.0 * position.z - 1.0, 1.0);\n"
"	out_velocity = vec2(velocity_pixels.x / screen_size.x, -velocity_pixels.y / screen_size.y);\n"
"}\n"
"";

const char* motionVectorFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 out_velocity;\n"
"layout(location = 0) out vec2 velocity;\n"
"\n"
"void main()\n"
"{\n"
"	velocity = out_velocity;\n"
"}\n"
"";

const char* downsampleFragmentSrc =
"#version 330 core\n"
"\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform float gamma;\n"
"uniform ivec2 dest_origin;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec4 WronskiFilter(ivec2 dst)\n"
"{\n"
"	const float d0 = 0.75777;\n"
"	const float d1 = 2.907;\n"
"	const float w0 = 0.37487566;\n"
"	const float w1 = -0.12487566;\n"
"	vec2 inv_source_size = 1.0 / vec2(textureSize(heh, 0));\n"
"	vec2 uv = (vec2(dst) * 2.0 + vec2(1.0)) * inv_source_size;\n"
"	vec4 c0 = texture(heh, uv + vec2( d0,  d0) * inv_source_size);\n"
"	vec4 c1 = texture(heh, uv + vec2(-d0,  d0) * inv_source_size);\n"
"	vec4 c2 = texture(heh, uv + vec2( d0, -d0) * inv_source_size);\n"
"	vec4 c3 = texture(heh, uv + vec2(-d0, -d0) * inv_source_size);\n"
"	vec4 c4 = texture(heh, uv + vec2( d1,  0.0) * inv_source_size);\n"
"	vec4 c5 = texture(heh, uv + vec2(-d1,  0.0) * inv_source_size);\n"
"	vec4 c6 = texture(heh, uv + vec2( 0.0,  d1) * inv_source_size);\n"
"	vec4 c7 = texture(heh, uv + vec2( 0.0, -d1) * inv_source_size);\n"
"	vec3 average = (ToDisplay(c0.rgb) + ToDisplay(c1.rgb) + ToDisplay(c2.rgb) + ToDisplay(c3.rgb)) * w0 +\n"
"		(ToDisplay(c4.rgb) + ToDisplay(c5.rgb) + ToDisplay(c6.rgb) + ToDisplay(c7.rgb)) * w1;\n"
"	float alpha = (c0.a + c1.a + c2.a + c3.a) * w0 + (c4.a + c5.a + c6.a + c7.a) * w1;\n"
"	return vec4(FromDisplay(average), clamp(alpha, 0.0, 1.0));\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	ivec2 dst = ivec2(gl_FragCoord.xy) - dest_origin;\n"
"	color = WronskiFilter(dst);\n"
"}\n"
"";

const char* bloomThresholdFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D depth_source;\n"
"uniform float gamma;\n"
"uniform float bloom_threshold;\n"
"uniform int use_depth_mask;\n"
"\n"
"vec3 ToDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(gamma));\n"
"}\n"
"\n"
"vec3 FromDisplay(vec3 sourcecolor)\n"
"{\n"
"	return pow(max(sourcecolor, vec3(0.0)), vec3(1.0 / max(gamma, 0.0001)));\n"
"}\n"
"\n"
"vec3 SampleBloom(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	vec2 sampleuv = uv + step * vec2(x, y);\n"
"	if (use_depth_mask != 0 && texture(depth_source, sampleuv).r >= 0.99999)\n"
"		return vec3(0.0);\n"
"	vec3 displaycolor = ToDisplay(texture(heh, sampleuv).rgb);\n"
"	float brightness = max(max(displaycolor.r, displaycolor.g), displaycolor.b);\n"
"	float threshold_range = max(1.0 - bloom_threshold, 0.0001);\n"
"	float amount = clamp((brightness - bloom_threshold) / threshold_range, 0.0, 1.0);\n"
"	return displaycolor * amount;\n"
"}\n"
"\n"
"vec3 SmoothBloomDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleBloom(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleBloom(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleBloom(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleBloom(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleBloom(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleBloom(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleBloom(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleBloom(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleBloom(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleBloom(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleBloom(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleBloom(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleBloom(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(FromDisplay(SmoothBloomDownsample(outuv, step)), 1.0);\n"
"}\n"
"";

const char* bloomDownsampleFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"\n"
"vec3 SampleWithStep(vec2 uv, vec2 step, float x, float y)\n"
"{\n"
"	return texture(heh, uv + step * vec2(x, y)).rgb;\n"
"}\n"
"\n"
"vec3 SmoothDownsample(vec2 baseuv, vec2 step)\n"
"{\n"
"	vec3 h0 = SampleWithStep(baseuv, step, -1.0,  1.0);\n"
"	vec3 h1 = SampleWithStep(baseuv, step,  1.0,  1.0);\n"
"	vec3 h2 = SampleWithStep(baseuv, step, -1.0, -1.0);\n"
"	vec3 h3 = SampleWithStep(baseuv, step,  1.0, -1.0);\n"
"	vec3 l0 = SampleWithStep(baseuv, step, -2.0,  2.0);\n"
"	vec3 l1 = SampleWithStep(baseuv, step,  0.0,  2.0);\n"
"	vec3 l2 = SampleWithStep(baseuv, step,  2.0,  2.0);\n"
"	vec3 l3 = SampleWithStep(baseuv, step, -2.0,  0.0);\n"
"	vec3 l4 = SampleWithStep(baseuv, step,  0.0,  0.0);\n"
"	vec3 l5 = SampleWithStep(baseuv, step,  2.0,  0.0);\n"
"	vec3 l6 = SampleWithStep(baseuv, step, -2.0, -2.0);\n"
"	vec3 l7 = SampleWithStep(baseuv, step,  0.0, -2.0);\n"
"	vec3 l8 = SampleWithStep(baseuv, step,  2.0, -2.0);\n"
"	return (h0 + h1 + h2 + h3) * 0.125 + (l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8) * 0.0555555;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 step = vec2(1.0) / vec2(textureSize(heh, 0));\n"
"	color = vec4(SmoothDownsample(outuv, step), 1.0);\n"
"}\n"
"";

const char* bloomMergeFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D MergeCur;\n"
"uniform sampler2D MergePrev;\n"
"uniform float bloomSpread;\n"
"\n"
"vec3 Blur3x3(sampler2D source, vec2 uv, vec2 scale)\n"
"{\n"
"	const float weights[9] = float[9](0.0625, 0.125, 0.0625, 0.125, 0.25, 0.125, 0.0625, 0.125, 0.0625);\n"
"	vec3 sum = vec3(0.0);\n"
"	int i = 0;\n"
"	for (int y = -1; y <= 1; y++)\n"
"	{\n"
"		for (int x = -1; x <= 1; x++, i++)\n"
"			sum += texture(source, uv + vec2(x, y) * scale).rgb * weights[i];\n"
"	}\n"
"	return sum;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	float blurScale = 1.5;\n"
"	vec3 curSample = texture(MergeCur, outuv).rgb;\n"
"	vec2 scaleUpsampled = vec2(blurScale) / vec2(textureSize(MergePrev, 0));\n"
"	vec3 upsampled = Blur3x3(MergePrev, outuv, scaleUpsampled);\n"
"	color = vec4(mix(curSample, upsampled, bloomSpread), 1.0);\n"
"}\n"
"";

const char* bloomCompositeFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D heh;\n"
"uniform sampler2D bloom;\n"
"uniform sampler2D scene_source;\n"
"uniform float gamma;\n"
"uniform float bloom_intensity;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 sourcecolor = texture(heh, outuv);\n"
"	vec3 scene_color = texture(scene_source, outuv).rgb;\n"
"	vec3 bloomcolor = texture(bloom, outuv).rgb * bloom_intensity;\n"
"	vec3 changed = abs(sourcecolor.rgb - scene_color);\n"
"	float changed_amount = max(max(changed.r, changed.g), changed.b);\n"
"	float scene_mask = 1.0 - smoothstep(0.002, 0.03, changed_amount);\n"
"	color = vec4(pow(max(sourcecolor.rgb + bloomcolor * scene_mask, vec3(0.0)), vec3(gamma)), 1.0);\n"
"}\n"
"";

const char* hbaoDeferredCompositeFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 color;\n"
"\n"
"uniform sampler2D final_source;\n"
"uniform sampler2D scene_source;\n"
"uniform sampler2D ao_scene_source;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 final_color = texture(final_source, outuv);\n"
"	vec3 scene_color = texture(scene_source, outuv).rgb;\n"
"	vec3 ao_scene_color = texture(ao_scene_source, outuv).rgb;\n"
"	vec3 changed = abs(final_color.rgb - scene_color);\n"
"	float changed_amount = max(max(changed.r, changed.g), changed.b);\n"
"	float scene_mask = 1.0 - smoothstep(0.002, 0.03, changed_amount);\n"
"	color = vec4(mix(final_color.rgb, ao_scene_color, scene_mask), final_color.a);\n"
"}\n"
"";

const char* testVertexSrc =
"#version 330 core\n"
"\n"
"layout(std140) uniform CommonBlock\n"
"{\n"
"	mat4 projection;\n"
"	mat4 modelview;\n"
"} commons;\n"
"\n"
"layout(location = 0) in vec3 position;\n"
"layout(location = 4) in vec2 uv;\n"
"layout(location = 5) in vec2 uv2;\n"
"\n"
"out vec2 outuv;\n"
"out vec2 outuv2;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 temp = commons.modelview * vec4(position, 1.0);\n"
"	gl_Position = commons.projection * vec4(temp.xyz, temp.w);\n"
"	outuv = uv;\n"
"	outuv2 = uv2;\n"
"}\n"
"";

const char* testFragmentSrc =
"#version 330 core\n"
"\n"
"uniform sampler2D colortexture;\n"
"uniform sampler2D lightmaptexture;\n"
"\n"
"in vec2 outuv;\n"
"in vec2 outuv2;\n"
"\n"
"out vec4 color;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 basecolor = texture(colortexture, outuv);\n"
"	color = vec4(basecolor.rgb * texture(lightmaptexture, outuv2).rgb, basecolor.a);\n"
"}\n"
"";

//-----------------------------------------------------------------------------
// HBAO (Horizon-Based Ambient Occlusion) shaders.
//
// Based on NVIDIA's HBAO formulation (Bavoil & Sainz, SIGGRAPH 2008) as
// adapted in the Unity reference example bundled with this engine. The
// algorithm walks rays in screen space from each pixel, computing the
// horizon angle relative to the surface normal at the sampled depth. The
// resulting AO factor is bilaterally blurred with depth weighting and
// then multiplied into the scene color.
//
// Inputs:
//   depth_tex : source depth reduced to the AO working resolution.
//   noise_tex : 4x4 noise (R8) for random sample rotation.
//
// View-space convention (in the AO shader):
//   x increases right, y increases up, z = +depth (positive into scene).
//   Reconstructed normal points TOWARD the camera (negative z).
//-----------------------------------------------------------------------------

const char* hbaoDepthFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"layout(location = 0) out vec4 result;\n"
"\n"
"uniform sampler2D depth_tex;\n"
"uniform sampler2DMS depth_ms_tex;\n"
"uniform int depth_samples;\n"
"uniform vec2 input_screen_size;\n"
"uniform vec2 ao_screen_size;\n"
"\n"
"float FetchDepth(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    if (depth_samples > 1)\n"
"    {\n"
"        float d = 1.0;\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= depth_samples) break;\n"
"            d = min(d, texelFetch(depth_ms_tex, pixel, i).r);\n"
"        }\n"
"        return d;\n"
"    }\n"
"    return texelFetch(depth_tex, pixel, 0).r;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    //Cost of this pass scaled with source_W * source_H regardless of\n"
"    //hbao_resolution, which is why the F2 slider used to barely move perf.\n"
"    //A fixed 2x2 min covers typical 2x-4x downsample ratios; the AO horizon\n"
"    //march is a low-frequency screen-space approximation and does not need\n"
"    //a conservative min over the entire source footprint.\n"
"    ivec2 ao_pixel = ivec2(gl_FragCoord.xy);\n"
"    ivec2 input_size = ivec2(input_screen_size);\n"
"    vec2 src_center = (vec2(ao_pixel) + vec2(0.5)) * (input_screen_size / ao_screen_size);\n"
"    ivec2 src_origin = ivec2(floor(src_center - vec2(0.5)));\n"
"    ivec2 p00 = clamp(src_origin,                  ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p10 = clamp(src_origin + ivec2(1, 0),    ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p01 = clamp(src_origin + ivec2(0, 1),    ivec2(0), input_size - ivec2(1));\n"
"    ivec2 p11 = clamp(src_origin + ivec2(1, 1),    ivec2(0), input_size - ivec2(1));\n"
"    float d = min(min(FetchDepth(p00), FetchDepth(p10)),\n"
"                  min(FetchDepth(p01), FetchDepth(p11)));\n"
"    result = vec4(d, 0.0, 0.0, 1.0);\n"
"}\n"
"";

const char* hbaoAOFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"layout(location = 0) out vec4 ao_out;\n"
"\n"
"uniform sampler2D depth_tex;\n"
"uniform sampler2D noise_tex;\n"
"\n"
"//Projection helpers: pack (2/m00, 2/m11, -1/m00, -1/m11) so that\n"
"//  view.xy = (uv * proj_info.xy + proj_info.zw) * depth;\n"
"uniform vec4 proj_info;\n"
"uniform vec2 near_far;       // (nearZ, farZ)\n"
"uniform float radius;        // world-space radius\n"
"uniform float radius_pixels; // pixel-space radius when depth == 1\n"
"uniform float max_radius_pixels;\n"
"uniform float neg_inv_radius2;\n"
"uniform float angle_bias;\n"
"uniform float ao_multiplier;\n"
"uniform vec2 inv_screen_size;\n"
"uniform vec2 ao_inv_screen_size;\n"
"uniform vec2 screen_size;\n"
"uniform vec2 temporal;       // (rotation_offset, jitter_offset)\n"
"uniform vec2 noise_scale;\n"
"uniform int directions;\n"
"uniform int steps;\n"
"\n"
"const float PI = 3.14159265358979323846;\n"
"\n"
"float linearize_depth(float d)\n"
"{\n"
"    //OpenGL clip-space z is [-1,1] after divide; FBO depth is [0,1].\n"
"    float z_n = 2.0 * d - 1.0;\n"
"    float n = near_far.x;\n"
"    float f = near_far.y;\n"
"    return (2.0 * n * f) / (f + n - z_n * (f - n));\n"
"}\n"
"\n"
"vec3 fetch_view_pos(vec2 uv)\n"
"{\n"
"    //Clamp UV to keep stray reads inside the buffer (HBAO's UV guard).\n"
"    uv = clamp(uv, vec2(0.0), vec2(1.0) - ao_inv_screen_size * 0.5);\n"
"    float d = linearize_depth(texture(depth_tex, uv).r);\n"
"    vec3 p;\n"
"    p.xy = (uv * proj_info.xy + proj_info.zw) * d;\n"
"    p.z = d;\n"
"    return p;\n"
"}\n"
"\n"
"vec3 min_diff(vec3 P, vec3 Pr, vec3 Pl)\n"
"{\n"
"    vec3 V1 = Pr - P;\n"
"    vec3 V2 = P - Pl;\n"
"    return (dot(V1, V1) < dot(V2, V2)) ? V1 : V2;\n"
"}\n"
"\n"
"vec3 reconstruct_normal(vec2 uv, vec3 P)\n"
"{\n"
"    vec3 Pr = fetch_view_pos(uv + vec2(ao_inv_screen_size.x, 0.0));\n"
"    vec3 Pl = fetch_view_pos(uv + vec2(-ao_inv_screen_size.x, 0.0));\n"
"    vec3 Pt = fetch_view_pos(uv + vec2(0.0, ao_inv_screen_size.y));\n"
"    vec3 Pb = fetch_view_pos(uv + vec2(0.0, -ao_inv_screen_size.y));\n"
"    //Cross(dx, dy) in our LH (x right, y up, z = +depth into scene) gives\n"
"    //+z = into the scene. We want a vector facing the camera, so negate.\n"
"    return -normalize(cross(min_diff(P, Pr, Pl), min_diff(P, Pt, Pb)));\n"
"}\n"
"\n"
"float falloff(float dist_sq)\n"
"{\n"
"    return dist_sq * neg_inv_radius2 + 1.0;\n"
"}\n"
"\n"
"float compute_ao(vec3 P, vec3 N, vec3 S)\n"
"{\n"
"    vec3 V = S - P;\n"
"    float VdotV = dot(V, V);\n"
"    float NdotV = dot(N, V) * inversesqrt(max(VdotV, 1e-6));\n"
"    return clamp(NdotV - angle_bias, 0.0, 1.0) * clamp(falloff(VdotV), 0.0, 1.0);\n"
"}\n"
"\n"
"vec2 fetch_noise(vec2 screen_pos)\n"
"{\n"
"    return texture(noise_tex, screen_pos / 4.0).rg;\n"
"}\n"
"\n"
"vec2 rotate_dir(vec2 dir, vec2 rot)\n"
"{\n"
"    return vec2(dir.x * rot.x - dir.y * rot.y,\n"
"                dir.x * rot.y + dir.y * rot.x);\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec3 P = fetch_view_pos(outuv);\n"
"    //Output linearized depth as the .y channel for the bilateral blur weight.\n"
"    float depth_for_blur = clamp(P.z / max(near_far.y, 1e-4), 0.0, 1.0);\n"
"\n"
"    //Avoid running on far-plane sky pixels.\n"
"    if (P.z >= near_far.y * 0.999)\n"
"    {\n"
"        ao_out = vec4(1.0, depth_for_blur, 0.0, 1.0);\n"
"        return;\n"
"    }\n"
"\n"
"    vec3 N = reconstruct_normal(outuv, P);\n"
"\n"
"    //Step size in pixels. Sample radius shrinks with depth (perspective).\n"
"    float step_pixels = min(radius_pixels / max(P.z, 1e-3), max_radius_pixels);\n"
"    step_pixels = step_pixels / float(steps + 1);\n"
"\n"
"    //Per-pixel noise: cos/sin angle in .r, sample jitter in .g.\n"
"    vec2 screen_pos = outuv * screen_size;\n"
"    vec2 rand = fetch_noise(screen_pos);\n"
"\n"
"    float alpha = 2.0 * PI / float(directions);\n"
"    float ao = 0.0;\n"
"    for (int d = 0; d < directions; ++d)\n"
"    {\n"
"        float angle = alpha * (float(d) + rand.x + temporal.x);\n"
"        vec2 dir = vec2(cos(angle), sin(angle));\n"
"        float ray_pixels = fract(rand.y + temporal.y) * step_pixels + 1.0;\n"
"        for (int s = 0; s < steps; ++s)\n"
"        {\n"
"            vec2 snapped_uv = (round(ray_pixels * dir) * ao_inv_screen_size) + outuv;\n"
"            vec3 S = fetch_view_pos(snapped_uv);\n"
"            ao += compute_ao(P, N, S);\n"
"            ray_pixels += step_pixels;\n"
"        }\n"
"    }\n"
"\n"
"    ao = ao * ao_multiplier;\n"
"    ao = clamp(1.0 - ao, 0.0, 1.0);\n"
"\n"
"    ao_out = vec4(ao, depth_for_blur, 0.0, 1.0);\n"
"}\n"
"";

const char* hbaoBlurFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D heh;       // RG: x=AO, y=linear depth in [0,1]\n"
"uniform vec2 blur_delta;     // (1/w, 0) or (0, 1/h)\n"
"uniform float sharpness;     // higher = sharper edges\n"
"uniform int kernel_radius;   // 0 means just passthrough\n"
"\n"
"void main()\n"
"{\n"
"    vec2 center = texture(heh, outuv).xy;\n"
"    float center_ao = center.x;\n"
"    float center_z = center.y;\n"
"    if (kernel_radius <= 0)\n"
"    {\n"
"        result = vec4(center_ao, center_z, 0.0, 1.0);\n"
"        return;\n"
"    }\n"
"    float sigma = float(kernel_radius) * 0.5;\n"
"    float falloff = 1.0 / (2.0 * sigma * sigma);\n"
"    float total_ao = center_ao;\n"
"    float total_w = 1.0;\n"
"    for (int r = 1; r <= 8; ++r)\n"
"    {\n"
"        if (r > kernel_radius) break;\n"
"        vec2 uv_p = outuv + float(r) * blur_delta;\n"
"        vec2 uv_n = outuv - float(r) * blur_delta;\n"
"        vec2 sp = texture(heh, uv_p).xy;\n"
"        vec2 sn = texture(heh, uv_n).xy;\n"
"        float dzp = (center_z - sp.y) * sharpness;\n"
"        float dzn = (center_z - sn.y) * sharpness;\n"
"        float wp = exp2(-float(r * r) * falloff - dzp * dzp);\n"
"        float wn = exp2(-float(r * r) * falloff - dzn * dzn);\n"
"        total_ao += sp.x * wp + sn.x * wn;\n"
"        total_w += wp + wn;\n"
"    }\n"
"    total_ao /= max(total_w, 1e-6);\n"
"    result = vec4(total_ao, center_z, 0.0, 1.0);\n"
"}\n"
"";

const char* hbaoTemporalFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D current_ao_tex;  // RG: x=AO, y=linear depth in [0,1]\n"
"uniform sampler2D history_tex;     // RG: x=accumulated AO, y=linear depth in [0,1]\n"
"uniform sampler2D depth_tex;\n"
"uniform sampler2D motion_tex;      // RG: current_uv - previous_uv\n"
"uniform sampler2DMS motion_ms_tex;\n"
"uniform mat4 current_inv_view_projection;\n"
"uniform mat4 previous_view_projection;\n"
"uniform int has_history;\n"
"uniform int has_motion;\n"
"uniform int motion_samples;\n"
"uniform vec2 input_screen_size;\n"
"uniform vec2 ao_screen_size;\n"
"uniform float history_weight;\n"
"\n"
"vec2 FetchMotion(ivec2 pixel)\n"
"{\n"
"	pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"	if (motion_samples > 1)\n"
"	{\n"
"		vec2 best = vec2(0.0);\n"
"		float best_len = 0.0;\n"
"		for (int i = 0; i < 8; ++i)\n"
"		{\n"
"			if (i >= motion_samples) break;\n"
"			vec2 m = texelFetch(motion_ms_tex, pixel, i).xy;\n"
"			float len_sq = dot(m, m);\n"
"			if (len_sq > best_len)\n"
"			{\n"
"				best = m;\n"
"				best_len = len_sq;\n"
"			}\n"
"		}\n"
"		return best;\n"
"	}\n"
"	return texelFetch(motion_tex, pixel, 0).xy;\n"
"}\n"
"\n"
"vec2 ObjectMotion(vec2 uv)\n"
"{\n"
"	if (has_motion == 0)\n"
"		return vec2(0.0);\n"
"	ivec2 ao_pixel = ivec2(gl_FragCoord.xy);\n"
"	ivec2 input_size = ivec2(input_screen_size);\n"
"	vec2 src_min_f = floor(vec2(ao_pixel) * input_screen_size / ao_screen_size);\n"
"	vec2 src_max_f = ceil(vec2(ao_pixel + ivec2(1)) * input_screen_size / ao_screen_size);\n"
"	ivec2 src_min = clamp(ivec2(src_min_f), ivec2(0), input_size - ivec2(1));\n"
"	ivec2 src_max = clamp(max(ivec2(src_max_f), src_min + ivec2(1)), ivec2(1), input_size);\n"
"	vec2 best = vec2(0.0);\n"
"	float best_len = 0.0;\n"
"	for (int y = 0; y < 8; ++y)\n"
"	{\n"
"		int py = src_min.y + y;\n"
"		if (py >= src_max.y) break;\n"
"		for (int x = 0; x < 8; ++x)\n"
"		{\n"
"			int px = src_min.x + x;\n"
"			if (px >= src_max.x) break;\n"
"			vec2 m = FetchMotion(ivec2(px, py));\n"
"			float len_sq = dot(m, m);\n"
"			if (len_sq > best_len)\n"
"			{\n"
"				best = m;\n"
"				best_len = len_sq;\n"
"			}\n"
"		}\n"
"	}\n"
"	return best;\n"
"}\n"
"\n"
"vec2 CameraMotion(vec2 uv, float depth)\n"
"{\n"
"	vec4 clip = vec4(uv * 2.0 - 1.0, depth * 2.0 - 1.0, 1.0);\n"
"	vec4 world = current_inv_view_projection * clip;\n"
"	if (abs(world.w) <= 0.000001)\n"
"		return vec2(1000.0);\n"
"	world /= world.w;\n"
"	vec4 prev_clip = previous_view_projection * world;\n"
"	if (prev_clip.w <= 0.000001)\n"
"		return vec2(1000.0);\n"
"	vec2 prev_uv = (prev_clip.xy / prev_clip.w) * 0.5 + 0.5;\n"
"	return uv - prev_uv;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"	vec2 cur = texture(current_ao_tex, outuv).xy;\n"
"	float raw_depth = texture(depth_tex, outuv).r;\n"
"	if (has_history == 0)\n"
"	{\n"
"		result = vec4(cur.x, cur.y, 0.0, 1.0);\n"
"		return;\n"
"	}\n"
"\n"
"	vec2 motion = CameraMotion(outuv, raw_depth);\n"
"	vec2 object_motion = ObjectMotion(outuv);\n"
"	if (dot(object_motion, object_motion) > 1e-10)\n"
"	{\n"
"		motion = object_motion;\n"
"	}\n"
"\n"
"	vec2 prev_uv = outuv - motion;\n"
"	if (any(lessThan(prev_uv, vec2(0.0))) || any(greaterThan(prev_uv, vec2(1.0))))\n"
"	{\n"
"		result = vec4(cur.x, cur.y, 0.0, 1.0);\n"
"		return;\n"
"	}\n"
"\n"
"	vec2 hist = texture(history_tex, prev_uv).xy;\n"
"	float depth_delta = abs(hist.y - cur.y);\n"
"	float depth_limit = max(0.00008, cur.y * 0.006);\n"
"	float current_min = cur.x;\n"
"	float current_max = cur.x;\n"
"	vec2 texel = 1.0 / vec2(textureSize(current_ao_tex, 0));\n"
"	for (int y = -1; y <= 1; ++y)\n"
"	{\n"
"		for (int x = -1; x <= 1; ++x)\n"
"		{\n"
"			float ao = texture(current_ao_tex, outuv + vec2(x, y) * texel).x;\n"
"			current_min = min(current_min, ao);\n"
"			current_max = max(current_max, ao);\n"
"		}\n"
"	}\n"
"	hist.x = clamp(hist.x, current_min - 0.12, current_max + 0.12);\n"
"	float depth_weight = 1.0 - smoothstep(depth_limit * 0.35, depth_limit, depth_delta);\n"
"	float motion_pixels = length(motion * input_screen_size);\n"
"	float motion_weight = 1.0 - smoothstep(6.0, 18.0, motion_pixels);\n"
"	float w = history_weight * depth_weight * motion_weight;\n"
"	result = vec4(mix(cur.x, hist.x, w), cur.y, 0.0, 1.0);\n"
"}\n"
"";

const char* hbaoSuppressionFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D existing_mask;\n"
"uniform sampler2DMS existing_mask_ms;\n"
"uniform sampler2D color_tex;\n"
"uniform sampler2DMS color_ms_tex;\n"
"uniform int has_mask;\n"
"uniform int use_bloom_mask;\n"
"uniform int source_samples;\n"
"uniform vec2 input_screen_size;\n"
"uniform vec2 ao_screen_size;\n"
"uniform float gamma;\n"
"uniform float bloom_threshold;\n"
"\n"
"float MaskAtPixel(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    if (source_samples > 1)\n"
"    {\n"
"        float mask = 0.0;\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= source_samples) break;\n"
"            mask = max(mask, texelFetch(existing_mask_ms, pixel, i).r);\n"
"        }\n"
"        return mask;\n"
"    }\n"
"    return texelFetch(existing_mask, pixel, 0).r;\n"
"}\n"
"\n"
"float BloomAmountFromColor(vec3 color)\n"
"{\n"
"    vec3 display_color = pow(max(color, vec3(0.0)), vec3(gamma));\n"
"    float brightness = max(max(display_color.r, display_color.g), display_color.b);\n"
"    float range = max(1.0 - bloom_threshold, 0.0001);\n"
"    return clamp((brightness - bloom_threshold) / range, 0.0, 1.0);\n"
"}\n"
"\n"
"float BloomAtPixel(ivec2 pixel)\n"
"{\n"
"    pixel = clamp(pixel, ivec2(0), ivec2(input_screen_size) - ivec2(1));\n"
"    if (source_samples > 1)\n"
"    {\n"
"        float bloom = 0.0;\n"
"        for (int i = 0; i < 8; ++i)\n"
"        {\n"
"            if (i >= source_samples) break;\n"
"            bloom = max(bloom, BloomAmountFromColor(texelFetch(color_ms_tex, pixel, i).rgb));\n"
"        }\n"
"        return bloom;\n"
"    }\n"
"    return BloomAmountFromColor(texelFetch(color_tex, pixel, 0).rgb);\n"
"}\n"
"\n"
"void SourceBlock(out ivec2 src_min, out ivec2 src_max)\n"
"{\n"
"    ivec2 ao_pixel = ivec2(gl_FragCoord.xy);\n"
"    ivec2 input_size = ivec2(input_screen_size);\n"
"    vec2 src_min_f = floor(vec2(ao_pixel) * input_screen_size / ao_screen_size);\n"
"    vec2 src_max_f = ceil(vec2(ao_pixel + ivec2(1)) * input_screen_size / ao_screen_size);\n"
"    src_min = clamp(ivec2(src_min_f), ivec2(0), input_size - ivec2(1));\n"
"    src_max = clamp(max(ivec2(src_max_f), src_min + ivec2(1)), ivec2(1), input_size);\n"
"}\n"
"\n"
"float MaskAmount()\n"
"{\n"
"    if (has_mask == 0)\n"
"        return 0.0;\n"
"    ivec2 src_min;\n"
"    ivec2 src_max;\n"
"    SourceBlock(src_min, src_max);\n"
"    float mask = 0.0;\n"
"    for (int y = 0; y < 8; ++y)\n"
"    {\n"
"        int py = src_min.y + y;\n"
"        if (py >= src_max.y) break;\n"
"        for (int x = 0; x < 8; ++x)\n"
"        {\n"
"            int px = src_min.x + x;\n"
"            if (px >= src_max.x) break;\n"
"            mask = max(mask, MaskAtPixel(ivec2(px, py)));\n"
"        }\n"
"    }\n"
"    return mask;\n"
"}\n"
"\n"
"float BloomAmount()\n"
"{\n"
"    if (use_bloom_mask == 0)\n"
"        return 0.0;\n"
"    ivec2 src_min;\n"
"    ivec2 src_max;\n"
"    SourceBlock(src_min, src_max);\n"
"    float bloom = 0.0;\n"
"    for (int y = 0; y < 8; ++y)\n"
"    {\n"
"        int py = src_min.y + y;\n"
"        if (py >= src_max.y) break;\n"
"        for (int x = 0; x < 8; ++x)\n"
"        {\n"
"            int px = src_min.x + x;\n"
"            if (px >= src_max.x) break;\n"
"            bloom = max(bloom, BloomAtPixel(ivec2(px, py)));\n"
"        }\n"
"    }\n"
"    return bloom;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    float suppression = MaskAmount();\n"
"    if (use_bloom_mask != 0)\n"
"    {\n"
"        float bloom = BloomAmount();\n"
"        suppression = max(suppression, bloom);\n"
"    }\n"
"    result = vec4(clamp(suppression, 0.0, 1.0), 0.0, 0.0, 1.0);\n"
"}\n"
"";

//Apply pass: multiplies destination color by the AO factor.
//Uses (GL_DST_COLOR, GL_ZERO) blend, so the output color is the AO multiplier.
const char* hbaoApplyFragmentSrc =
"#version 330 core\n"
"\n"
"in vec2 outuv;\n"
"out vec4 result;\n"
"\n"
"uniform sampler2D heh;       // RG: x=AO factor 0..1, y=depth\n"
"uniform sampler2D suppression_mask; // R8: 0=apply AO, 1=suppress AO\n"
"uniform float intensity;     // 0..4-ish; AO raised to this power\n"
"uniform int has_suppression_mask;\n"
"\n"
"void main()\n"
"{\n"
"    vec2 ao_depth = texture(heh, outuv).xy;\n"
"    float ao = ao_depth.x;\n"
"    ao = clamp(ao, 0.0, 1.0);\n"
"    ao = pow(ao, intensity);\n"
"    if (has_suppression_mask != 0)\n"
"    {\n"
"        float suppression = clamp(texture(suppression_mask, outuv).r, 0.0, 1.0);\n"
"        ao = mix(ao, 1.0, suppression);\n"
"    }\n"
"    result = vec4(vec3(ao), 1.0);\n"
"}\n"
"";
